### ISSUE TITLE
UnicodeEncodeErrors on Windows

### ISSUE THREAD

**Issue by reevespaul** [FirebirdSQL/firebird-qa#3]
I'm getting around 20 errors like this one for core 1331 when running under windows 2019 server.
```
UnicodeEncodeError: 'charmap' codec can't encode characters in position 221-225: character maps to <undefined>
```

They don't show when run under linux.
Does anyone have any idea what I'm missing? I've tried with python 3.8 and 3.9

**Comment by pcisar** [comment]
Could you please provide a name of at least one such test?

**Comment by reevespaul** [comment]
It is in the first line :-) - core 1331

**Comment by reevespaul** [comment]
For what its worth I've already tried
```
PYTHONIOENCODING=UTF-8
PYTHONLEGACYWINDOWSSTDIO=UTF-8
```
That hasn't worked.

I tried this first on server core, which is console only. Everything needs to be configured manually and thought maybe that I might have missed something. But my latest tests are with a fully configured GUI version of W2K19.
